name: Continuous Integration

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node
        id: setup-node
        uses: 7H3LaughingMan/pf2e-types/.github/actions/setup-node.yml@v13
        with:
          use-cache: true

      - run: npm run tsc

      - run: npm run eslint
