name: Continuous Integration

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v6

      - name: Setup Node
        id: setup-node
        uses: ./.github/actions/setup-node
        with:
          use-cache: true

      - run: npm run tsc

      - run: npm run eslint
