name: Update Foundry Types

on:
  repository_dispatch:
    types: [foundry-types]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v6

      - name: Setup Node
        id: setup-node
        uses: actions/setup-node@v6
        with:
          node-version: 24
          package-manager-cache: false

      - name: Clean Install
        id: clean-install
        run: npm ci

      - name: Update
        id: update
        run: npm update foundry-types

      - name: Setup Git
        id: setup-git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Stage, Commit, Push
        id: stage-commit-push
        run: |
          git add .
          git commit -m "Updating foundry-types"
          git push origin HEAD:${GITHUB_REF}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
