name: Update Foundry Types

on:
  repository_dispatch:
    types: [foundry-types]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Setup Node
        id: setup-node
        uses: 7H3LaughingMan/pf2e-types/.github/actions/setup-node@v13

      - name: Update
        id: update
        run: npm update foundry-types

      - name: Commit Files
        id: commit-files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git commit -a -m "Updating foundry-types"

      - name: Push Files
        id: push-files
        uses: ad-m/github-push-action@v1.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
